name: will_store
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  string_validator: ^1.0.0
  cloud_firestore: ^4.5.2
  firebase_core: ^2.10.0
  fake_cloud_firestore: ^2.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  parameterized_test: ^1.0.0

flutter:
  uses-material-design: true
